# Generated by Django 3.0.6 on 2020-05-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=300)),
                ('small_image', models.ImageField(upload_to='Intro_Mobiles')),
                ('available', models.BooleanField(default=True)),
                ('view_image', models.ImageField(upload_to='View_Mobiles')),
                ('description', models.TextField()),
                ('discount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.Category')),
                ('sub_categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.SubCategory')),
            ],
        ),
    ]
