# Generated by Django 3.0.6 on 2020-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_auto_20200529_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default='test-product', max_length=100),
            preserve_default=False,
        ),
    ]
