# Generated by Django 3.0.6 on 2020-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0006_auto_20200529_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is description'),
            preserve_default=False,
        ),
    ]
