# Generated by Django 3.0.6 on 2020-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0008_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
