# Generated by Django 3.0.6 on 2020-06-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0014_auto_20200620_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(max_length=100),
        ),
    ]
