# Generated by Django 3.0.6 on 2020-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0017_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='amount',
            field=models.FloatField(),
        ),
    ]
