# Generated by Django 3.0.6 on 2020-06-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0022_address_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
