# Generated by Django 3.0.6 on 2020-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0025_auto_20200630_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='one_click_purchasing',
            field=models.BooleanField(),
        ),
    ]
