# Generated by Django 3.0.6 on 2020-07-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0027_auto_20200701_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
